[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = { NOT = { Path = ["/config.yml", "/index.html", "*.yml", "*.yaml", "*.json", "*.xml", "*.txt", "*.js", "*.css", "*.woff", "*.woff2", "*.ttf", "*.eot", "*.svg", "*.png", "*.jpg", "*.jpeg", "*.gif", "*.ico"] } }

[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/config.yml"
  [headers.values]
    Content-Type = "application/x-yaml; charset=utf-8"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
