backend:
  name: git-gateway
  branch: main

# These lines should *not* be indented
media_folder: 'public/images/uploads' # Media files will be stored in the repo under public/images/uploads
public_folder: '/images/uploads' # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: 'menus'
    label: 'Menus'
    label_singular: 'Menu'
    folder: 'src/_menus'
    create: true
    slug: '{{slug}}'
    nested: { depth: 100, subfolders: false }
    meta: { path: { widget: 'string', label: 'Path' } }
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Effective Date',
          name: 'date',
          widget: 'datetime',
          date_format: 'YYYY-MM-DD',
          time_format: false,
          default: '{{now}}',
        }
      - { label: 'Menu File', name: 'menuFile', widget: 'file' }
  - name: 'specials'
    label: 'Featured Menu Items'
    label_singular: 'Featured Menu Item'
    folder: 'src/_specials'
    create: true
    slug: '{{slug}}'
    nested: { depth: 100, subfolders: false }
    meta: { path: { widget: 'string', label: 'Path' } }
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Weekly Special?', name: 'isWeeklySpecial', widget: 'boolean' }
      - { label: 'Item Name', name: 'itemName', widget: 'string' }
      - { label: 'Item Image', name: 'itemImage', widget: 'image' }
      - { label: 'Item Description', name: 'itemDescription', widget: 'string' }
      - {
          label: 'Item Note',
          name: 'itemNote',
          widget: 'string',
          required: false,
        }
      - { label: 'Item Price', name: 'itemPrice', widget: 'number' }
  - name: 'happy_hour'
    label: 'Happy Hour'
    folder: 'src/_happy_hour'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Day of the Week',
          name: 'dayOfWeek',
          widget: 'select',
          multiple: true,
          options:
            [
              'Monday',
              'Tuesday',
              'Wednesday',
              'Thursday',
              'Friday',
              'Saturday',
              'Sunday',
            ],
          required: false,
        }
      - {
          label: 'Start Time',
          name: 'startTime',
          widget: 'datetime',
          date_format: false,
          time_format: 'HH:mm',
          required: false,
        }
      - {
          label: 'End Time',
          name: 'endTime',
          widget: 'datetime',
          date_format: false,
          time_format: 'HH:mm',
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'event_onetime'
    label: 'One-Time Event'
    folder: 'src/_events/onetime'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Promo Image', name: 'flyer', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'event_recurring'
    label: 'Recurring Event'
    folder: 'src/_events/recurring'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Initial Date', name: 'date', widget: 'datetime' }
      - { label: 'End Date', name: 'endDate', widget: 'datetime' }
      - { label: 'Promo Image', name: 'flyer', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - {
          label: 'Recurring Frequency',
          name: 'recurringFrequency',
          widget: 'select',
          options: ['Daily', 'Weekly', 'Monthly'],
        }
  - name: 'images'
    label: 'Images'
    label_singular: 'Image'
    folder: 'src/_images'
    create: true
    slug: '{{slug}}'
    nested: { depth: 100, subfolders: false }
    meta: { path: { widget: 'string', label: 'Path' } }
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Image Title', name: 'imageTitle', widget: 'string' }
      - { label: 'Image File', name: 'imageFile', widget: 'file' }
  - name: 'content'
    label: 'Content'
    folder: 'src/_content/'
    create: true
    slug: '{{slug}}'
    nested: { depth: 100, subfolders: false }
    meta: { path: { widget: 'string', label: 'Path' } }
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Order',
          name: 'order',
          widget: 'number',
          hint: 'Display order on the page (lower numbers appear first)',
        }
      - { label: 'Image', name: 'image', widget: 'image', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'hours'
    label: 'Hours'
    folder: 'src/_hours'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Day',
          name: 'day',
          widget: 'select',
          multiple: true,
          options:
            [
              'Monday',
              'Tuesday',
              'Wednesday',
              'Thursday',
              'Friday',
              'Saturday',
              'Sunday',
            ],
        }
      - {
          label: 'Open Time',
          name: 'openTime',
          widget: 'datetime',
          date_format: false,
          time_format: 'HH:mm',
          required: false,
        }
      - {
          label: 'Close Time',
          name: 'closeTime',
          widget: 'datetime',
          date_format: false,
          time_format: 'HH:mm',
          required: false,
        }
      - { label: 'Closed', name: 'closed', widget: 'boolean', default: false }
      - { label: 'Notes', name: 'notes', widget: 'string', required: false }
