backend:
  name: git-gateway
  branch: main

# These lines should *not* be indented
media_folder: 'public/images/uploads' # Media files will be stored in the repo under public/images/uploads
public_folder: '/images/uploads' # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: 'menu'
    label: 'Menu'
    icon: 'utensils'
    collections:
      - name: 'main_menu'
        label: 'Main Menu'
        folder: '_menus/main'
        create: true
        slug: '{{slug}}'
        fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'menu' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Effective Date', name: 'date', widget: 'datetime' }
          - { label: 'Menu File', name: 'menuFile', widget: 'file' }
      - name: 'beer_menu'
        label: 'Beer Menu'
        folder: '_menus/beer'
        create: true
        slug: '{{slug}}'
        fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'menu' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Effective Date', name: 'date', widget: 'datetime' }
          - { label: 'Menu File', name: 'menuFile', widget: 'file' }
      - name: 'wine_menu'
        label: 'Wine Menu'
        folder: '_menus/wine'
        create: true
        slug: '{{slug}}'
        fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'menu' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Effective Date', name: 'date', widget: 'datetime' }
          - { label: 'Menu File', name: 'menuFile', widget: 'file' }
      - name: 'specials'
        label: 'Specials'
        icon: 'star'
        collections:
          - name: 'main_specials'
            label: 'Main Specials'
            folder: '_menus/specials/main'
            create: true
            slug: '{{slug}}'
            fields:
              - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'menu' }
              - { label: 'Item Name', name: 'itemName', widget: 'string' }
              - { label: 'Item Image', name: 'itemImage', widget: 'image' }
              - { label: 'Item Description', name: 'itemDescription', widget: 'string' }
              - { label: 'Item Note', name: 'itemNote', widget: 'string' }
              - { label: 'Item Price', name: 'itemPrice', widget: 'string' }
          - name: 'beer_specials'
            label: 'Beer Specials'
            folder: '_menus/specials/beer'
            create: true
            slug: '{{slug}}'
            fields:
              - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'menu' }
              - { label: 'Item Name', name: 'itemName', widget: 'string' }
              - { label: 'Item Image', name: 'itemImage', widget: 'image' }
              - { label: 'Item Description', name: 'itemDescription', widget: 'string' }
              - { label: 'Item Note', name: 'itemNote', widget: 'string' }
              - { label: 'Item Price', name: 'itemPrice', widget: 'string' }
          - name: 'wine_specials'
            label: 'Wine Specials'
            folder: '_menus/specials/wine'
            create: true
            slug: '{{slug}}'
            fields:
              - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'menu' }
              - { label: 'Item Name', name: 'itemName', widget: 'string' }
              - { label: 'Item Image', name: 'itemImage', widget: 'image' }
              - { label: 'Item Description', name: 'itemDescription', widget: 'string' }
              - { label: 'Item Note', name: 'itemNote', widget: 'string' }
              - { label: 'Item Price', name: 'itemPrice', widget: 'string' }
      - name: 'catering_menu'
        label: 'Catering Menu'
        folder: '_menus/catering'
        create: true
        slug: '{{slug}}'
        fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'menu' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Effective Date', name: 'date', widget: 'datetime' }
          - { label: 'Menu File', name: 'menuFile', widget: 'file' }
  - name: 'events'
    label: 'Events'
    icon: 'calendar'
    collections:
      - name: 'event_onetime'
        label: 'One-Time Event'
        folder: '_events/onetime'
        create: true
        slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
        fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'event' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Date', name: 'date', widget: 'datetime' }
          - { label: 'Promo Image', name: 'flyer', widget: 'image' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - name: 'event_recurring'
        label: 'Recurring Event'
        folder: '_events/recurring'
        create: true
        slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
        fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'event' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Initial Date', name: 'date', widget: 'datetime' }
          - { label: 'End Date', name: 'endDate', widget: 'datetime' }
          - { label: 'Promo Image', name: 'flyer', widget: 'image' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - {
              label: 'Recurring Frequency',
              name: 'recurringFrequency',
              widget: 'select',
              options: ['Daily', 'Weekly', 'Monthly'],
            }
  - name: 'images'
    label: 'Images'
    icon: 'image'
    collections:
      - name: 'home_images'
        label: 'Home Images'
        folder: '_images/home'
        create: true
        slug: '{{slug}}'
        fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'image' }
          - { label: 'Image File', name: 'imageFile', widget: 'file' }
      - name: 'catering_images'
        label: 'Catering Images'
        folder: '_images/catering'
        create: true
        slug: '{{slug}}'
        fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'image' }
          - { label: 'Image File', name: 'imageFile', widget: 'file' }
      - name: 'about_images'
        label: 'About Images'
        folder: '_images/about'
        create: true
        slug: '{{slug}}'
        fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'image' }
          - { label: 'Image File', name: 'imageFile', widget: 'file' }
      - name: 'reservations_images'
        label: 'Reservations Images'
        folder: '_images/reservations'
        create: true
        slug: '{{slug}}'
        fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'image' }
          - { label: 'Image File', name: 'imageFile', widget: 'file' }
      - name: 'events_images'
        label: 'Events Images'
        folder: '_images/events'
        create: true
        slug: '{{slug}}'
        fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'image' }
          - { label: 'Image File', name: 'imageFile', widget: 'file' }
